const OWNERSHIP_TYPES = {
    KYRIA: 0,
    EPICARPIA: 1,
    KYRIA_AND_EPICARPIA: 2,
    NOMEAS: 3,
    YPEREKMISTHOTIS: 4
};

const CONTRACT_TYPES = {
    RESIDENTIAL: 0,
    COMMERCIAL: 1,
    SHORT_TERM: 2,
    AGRICULTURAL: 3,
    GRANT_OF_USE: 4,
    OTHER: 5
};

const PROPERTY_TYPES = {
    APARTMENT: 0,
    HOUSE: 1,
    STORE: 2,
    OFFICE: 3,
    OUTDOOR_SPACE: 4,
    WAREHOUSE: 5,
    AGRICULTURAL: 6,
    PARKING_SPACE: 7,
    CAR_PARKS: 8,
    INDUSTRIAL: 9,
    HOTEL: 10,
    HOSPITAL: 11,
    BOARDING_INSTITUTION: 12,
    EDUCATION: 13,
    SPORT_FACILITIES: 14,
    THEATER: 15,
    CONFERENCE_HALL: 16,
    EXHIBITION_CENTER: 17,
    STADIUM: 18
}

module.exports = { OWNERSHIP_TYPES, CONTRACT_TYPES, PROPERTY_TYPES };